name: pakage the resources for maven
on:
  workflow_dispatch:

jobs:
  package:
      name: package
      runs-on: ubuntu-latest
  
      steps:

      - name: checkout
        uses: actions/checkout@master
        with:
          repository: adityadhopade/java-db-Login
      
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'