name: pakage the resources for maven build
on:
  workflow_dispatch:

jobs:
  package:
      name: package-maven-build
      runs-on: ubuntu-latest
  
      steps:

      - name: checkout
        uses: actions/checkout@master
        with:
          repository: adityadhopade/java-db-Login
      
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: build maven package
        run: mvn clean package
        
      - name: deploy the packaged artifact
        run: aws s3 cp target/*.war s3://artifactwarapplications3adityadhopade  
