name: Provisioning of threee tier architecture using Terraform
on: 
  workflow_dispatch: 
  push:
    branches: [main]

jobs: 
  provison-three-tier: 
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
      TF_VAR_mykey : ${{secrets.ssh_private_key}}
      TF_VAR_db_user_name: ${{ secrets.db_user_name }}
      TF_VAR_db_password: ${{ secrets.db_password }}
      
    steps:
      - name: checkout
        uses: actions/checkout@v2 

      - name: setup terraform
        id: setup-tf
        uses: hashicorp/setup-terraform@v2

      - name: terraform init
        id: init-tf
        run: terraform init
        
      - name: format terraform
        id: fmt-tf
        run: terraform fmt

      - name: terraform validate
        id: valid-tf
        run: terraform validate

      - name: terraform plan
        id: plan-tf
        run: terraform plan -input=false -lock=false

      - name: apply terraform 
        id: apply-tf
        run: terraform apply --auto-approve -lock=false